### ISSUE TITLE
If not in HTML5Mode, Google Analytics removes # and records pageview as /

### ISSUE THREAD

**Issue by timelf123** [angulartics/angulartics#109]
We cannot run our app in HTML5mode yet, so our links look like `site.com/#/route/page/example` rather than (w/ html5mode enabled links) `site.com/route/page/example`

When angulartics fires the GA pageview event, it passes an explicit path using `$location.path()` -- this works great and pages show up as `/route/page/example` in the reporting interface. The problem appears when you send events after the first pageview. Because the `#` (and everything after) is stripped by GA in processing, firing a generic event causes the page being tracked in GA to reset from `/route/page/example` to simply `/`. To duplicate, bring up the realtime analytics, view your site, and generate an event. 

From https://developers.google.com/analytics/devguides/collection/analyticsjs/pages :

> Note: While the anchor, or hash, portion of the URL is sent to Google Analytics, the value is processed out and will not show up in the page value within the final reports. To preserve the anchor, you must override the default page value.

We have temporarily patched this by explicitly passing a path with our events, but it is less than ideal.

Example:

```
ga('send', 'event', 'category', 'action', {'page': '/route/page/example'});
```

Associated code in angulartics-ga.js (note addition of {'page': properties.path} )

```
  $analyticsProvider.registerEventTrack(function (action, properties) {
    if (window._gaq) {
      _gaq.push(['_trackEvent', properties.category, action, properties.label, properties.value, properties.noninteraction]);
    }
    else if (window.ga) {
      if (properties.noninteraction) {
        ga('send', 'event', properties.category, action, properties.label, properties.value, {nonInteraction: 1, 'page': properties.path});
      } else {
        ga('send', 'event', properties.category, action, properties.label, properties.value, {'page': properties.path});
      }
    }
  });
```

**Comment by aendrew** [comment]
Please reopen — I often don't use HTML5 mode for various reasons and this issue affects me. Thanks!
