### ISSUE TITLE
Support for ui-router

### ISSUE THREAD

**Issue by ticky** [angulartics/angulartics#110]
Our app uses [ui-router's](https://github.com/angular-ui/ui-router) `$stateProvider` in place of the built-in `$routeProvider`.

Adding support for this should, as far as I can tell, involve a simple change to the `run` block [here](https://github.com/luisfarzati/angulartics/blob/master/src/angulartics.js#L88-L94) and adding a check like this;

``` javascript
if ($injector.has('$routeProvider')) {
    $rootScope.$on('$locationChangeSuccess', function (event, current) {
        '…'
    });
}
if ($injector.has('$stateProvider')) {
    $rootScope.$on('$stateChangeSuccess', function (event, current) {
        '…'
    });
}
```

**Comment by ElanHasson** [comment]
@luisfarzati has this been resolved? I'm using angular-ui router and When i reference the angulartics modules none of my routes work except my default route.

**Comment by chrismendis** [comment]
@ElanHasson my fix for this issue was merged on May 23, 2014: https://github.com/luisfarzati/angulartics/commit/f6a49d5dd6ff5febb483f9fcd4513b30729ecd2c. Perhaps there was a regression? You can run the angulartics tests, to see if the specs for this feature is still working.

**Comment by albertpeiro** [comment]
How do you track pages as "static" when you don't want to use router? I can't seem to get it working with: 

    $analyticsProvider.virtualPageviews(false);
    $analyticsProvider.firstPageview(true); /* Records pages that don't use $state or $route */
    $analyticsProvider.withAutoBase(true);  /* Records full path */

The only way it works is if I do in config:

$urlRouterProvider.otherwise('');
        $stateProvider
            .state('undefined', {
                url: '',
            });

Use case is about.html you get the gist. No functionality, but still need analytics and I want minimum effort and seamless integration

**Comment by yorch** [comment]
Same problem here, not working with ui-router

**Comment by sdornan** [comment]
It's also not working for me.

**Comment by chrismendis** [comment]
My fix from May 2014 is still on angulartics/master, so there may have been a regression in ui-router. Has anyone tried doing a git-bisect on ui-router to identify the commit that introduced the issue?

**Comment by tommymcdonald** [comment]
Currently not working for me with UI-Router either. Is there any progress on a fix?

**Comment by natedsaint** [comment]
Just ran into this some months after last comment. Not sure if we'll approach fixing it or just go a different route for our analytics package.

**Comment by timelf123** [comment]
Is it the auto page tracking that is not working on ui-router?

**Comment by natedsaint** [comment]
So, it looks like I was wrong: we ARE using ui-router but the problem was actually our analytics settings. Let me verify and if so I'll update.

**Comment by natedsaint** [comment]
Verified, ui-router is tracking page view changes with angulartics for us.
