### ISSUE TITLE
Register _setCustomVar for GA

### ISSUE THREAD

**Issue by jbarbede** [angulartics/angulartics#127]
Hi, any chance to set Custom Variables for Google Analytics?

Thanks

**Comment by anandp504** [comment]
@timelf123 The custom variable is not being sent to google analytics. Can you please let me know if I am doing something wrong? I couldn't use _setCustomVar(index, name, value, opt_scope) as _setCustomVar function wasn't available.

Global configuration (This gets imported into all pages)
ga('create', 'UA-xxxxx', 'auto');
ga('send', 'pageview');
var _gaq = _gaq || [];

In a particular page:
gaq.push(["_setCustomVar", 1, "user_id", loginModel.getUserId()]);
_gaq.push(['_trackPageview']);

**Comment by timelf123** [comment]
>gaq.push(["_setCustomVar", 1, "user_id", loginModel.getUserId()]);
Could it be `_qaq` instead of `qaq`?

**Comment by anandp504** [comment]
@timelf123 I am using the new code. So how do we set custom variables in the new code?

(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-XXXXXX-1', { 'siteSpeedSampleRate': 50 });
  ga('send', 'pageview');
  var _gaq = _gaq || [];

**Comment by anandp504** [comment]
@timelf123 Thanks for pointing me to the custom dimensions in GA. I was able to send a custom dimension with an event. However, angulartics automatically tracks pageviews. If I have to send a custom dimension with a pageTrack event, I will have to modify the angulartics-ga.js code itself. Is there a better way of doing it?

**Comment by timelf123** [comment]
@anandp504 no problem. You could turn off auto pageview tracking and do things manually (set dimension, call $analytics page track method), or set the custom dimension somewhere before the auto page tracking has a chance to run (in the resolve function of your router for example).

**Comment by anandp504** [comment]
@timelf123 Thank you very much. It was very helpful. I was able to set the custom variable in our router and we did not even have to disable the auto pageview tracking. The custom variables propogated to GA. Appreciate your help.

**Comment by rlucha** [comment]
+1

**Comment by rlucha** [comment]
I found the following solution: If an event is fired it will trigger a beacon with the custom variables attached. 

```
 $analyticsProvider.registerSetCustomVariable(function (index, value) { 
   if (window.ga) {
      
      ga('set', 'dimension' + index, value);
      ga('send', 'event', 'customVariable', 'set', 'customVariable', 0);
    }
  });
```
You should add 'setCustomVariable' to knownHandlers in angulartics.js to be able to register the call. then you can use it like:

```
$analytics.setCustomVariable(dimension, data);
```

This way you do not need to put the call before resolving the route/state.

**Comment by perqa** [comment]
I am very interested in this subject, but I find it strange that you use custom *variables* together with the new analytics.js. Referring to Google:
----
"Custom dimensions should be used in Universal Analytics where custom variables are used in the Classic Analytics ga.js JavaScript library."
----
Ref: https://support.google.com/analytics/answer/2795983?hl=en

Does angulartics not yet support custom dimensions, or is it just a name change from Google's side?

**Comment by rlucha** [comment]
My bad, I was referring to dimensions but used the old syntax for the example.
