### ISSUE TITLE
Non-jQuery dependent Waypoint-like method to track analytics within div scrolling

### ISSUE THREAD

**Issue by stvhanna** [angulartics/angulartics#140]
It would be nice to not have to use jQuery and the jQuery.Waypoint plugin to track analytics of elements passing through the viewport as they are scrolled by within a scrollable div container/parent (not Window/Document).

I've found https://github.com/thenikso/angular-inview, which doesn't require jQuery, but I'm not sure how to integrate it. Anyone has some suggestions on a way to do this? I'd greatly appreciate it. :)

**Comment by luisfarzati** [comment]
We just started splitting plugins off the core. This includes jQuery and waypoints. See #377 and https://github.com/angulartics/angulartics-google-analytics

**Comment by hermansje** [comment]
Waypoints works with adapters now, and has added support for usage with Zepto or without any DOM framework.

**Comment by luisfarzati** [comment]
Great, so we'll move the scroll tracking off the core and remove jQuery in the process.

**Comment by martinmcwhorter** [comment]
+1 Great work.
