### ISSUE TITLE
Make track methods return a promise

### ISSUE THREAD

**Issue by commjoen** [angulartics/angulartics#169]
I am currently in the situation where I sometimes need to do a redirect, but do want to trigger an analytics event that explains the reason of this redirect. However, sometimes the redirect is finished before the eventTrack is, so that I do not get this event.
My question is: how can I fix this? Is there a way to do an onComplete or a promise resolving?

Thanks!

**Comment by luisfarzati** [comment]
Sorry for the late response. I like where this was going. @commjoen did you ever make progress with this? And why do you say that the promise approach would break the setup of angulartics?

@ken210: it seems #247 resolves this in a cleaner way. Thanks for your contrib anyway.

**Comment by commjoen** [comment]
Hi, sorry, I was waiting for your response and was moving to other non-angular projects in the mean time. I will start on this somewhere next month hopefully.

**Comment by commjoen** [comment]
I would like to close the issue as time can tell i never found a good spot to progress this. Apologies!
