### ISSUE TITLE
pageTrack is fired twice for the first page

### ISSUE THREAD

**Issue by websirnik** [angulartics/angulartics#182]
When the first page loads, I get two calls to `$analyticsProvider.registerPageTrack` which results in 2 pageviews instead of 1 in GA and Piwik.
After some debugging, looks like the first call is done after jQuery bootstrap and the second is done on successful $state change.
Need to ignore the first call somehow.
Here is the stacktrace to `$analyticsProvider.registerPageTrack` calls when opening the first page:
![screen shot 2014-08-21 at 11 01 15](https://cloud.githubusercontent.com/assets/282871/3994458/5157d012-291a-11e4-97ee-9ec3bbea1849.png)

**Comment by devisree** [comment]
Hi,

Im getting two image request on login page using sitecatalyst.What could be the reason ?
