### ISSUE TITLE
Is it possible to set GA userId?

### ISSUE THREAD

**Issue by apitts** [angulartics/angulartics#193]
I have been trying to set this up with angulartics but have not yet been able to get it to work yet.  I have added this code to my SignIn and SignUp Controllers:
ga("set", "&uid", user._id.toString());

And have set up userId tracking in GA.  But userId information does not appear to be transmitted.  Should it work out of the box or am I missing something?  Thanks.

**Comment by ajbraus** [comment]
Can you clarify what you did? Maybe do a doc pull request for how to set this up? Thx!

**Comment by apitts** [comment]
Sure @ajbraus!  You may find this link useful: https://developers.google.com/analytics/devguides/collection/analyticsjs/

Basically you just need to add the below as per the link:
```
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-XXXX-Y', 'auto');
```

where  'UA-XXXX-Y' is your tracking id. 

Then elsewhere in your application (e.g. at login and signup) use something like the below:

```
  $scope.submitForm = function(event, isValid) {
    event.preventDefault();
    // check to make sure the form is completely valid
    if(isValid) {
      SecurityService.login($scope.user).success(function (user) {
        ga('set', '&uid', user._id.toString()); 
      });
    }
  };
 ```

My issue was that after success I redirect the user back to '/', which was resetting Google Analytics.  I just added a simple if statement on the index page to fix this, i.e. only create the tracking code if the user hasn't signed up or logged in already.  

Hope this helps!
