### ISSUE TITLE
The 'jquery-waypoints' and 'sha-1' is necessary?

### ISSUE THREAD

**Issue by TossShinHwa** [angulartics/angulartics#209]
I found it at [dependencies of bower.js](https://github.com/luisfarzati/angulartics/blob/master/bower.json#L24-L25), is there necessary? Maybe we should split them.

Any ideas?

**Comment by jrobertsatquoininc** [comment]
Any ETA on splitting out SHA-1 and Waypoint

**Comment by goncalomarques** [comment]
@lunks any estimation to solve this?

**Comment by timelf123** [comment]
This is solved in master. Should be cutting a release in the next few weeks once I have time to test everything

**Comment by bluesliverx** [comment]
+1, any update on this?

**Comment by ripper2hl** [comment]
:+1:  please resolve this!!

**Comment by timelf123** [comment]
Jquery dep is removed in 1.0.0

SHA1 is needed only by Marketo. Once the Marketo plugin is moved to it's own repo I will remove the SHA-1 dep. @rayrrr are you down to take on this task? I merged your changes from https://github.com/angulartics/angulartics/pull/394 but this should really be moved to its own repo. Let me know if you have any questions or don't have time to split off Marketo right now
