### ISSUE TITLE
Event Tracking with Piwik

### ISSUE THREAD

**Issue by andhofmt** [angulartics/angulartics#270]
Angulartics,

I've tried to run your product in our single page web application, hooked up to Piwik Analytics.

I included Piwik in the App.js, Index.html & I added some tracking code to a href events.

How do I make sure all of these go back to MY Piwik server. I did not find anywhere in the documentation where I actually hook up the Angulartics library with my tracking code. 

I'm trying to track button clicks if that helps.

- Andrew

**Comment by nidico** [comment]
We're having the same question.

Looking at the [piwik sample](https://github.com/luisfarzati/angulartics/blob/master/samples/piwik.html) proposes actually inserting the piwik tracking script snippet into the html. This however is a bit confusing - I would have expected to just configure the API endpoint in angulartics-piwik.

Any insights?

**Comment by kavi87** [comment]
+1

**Comment by Atlmapper** [comment]
+1

**Comment by j-brown** [comment]
+1

**Comment by postalservice14** [comment]
I want to make sure I understand the problem....  Are events not getting back to PIWIK for you?  Basically Angulartics-piwik expects the _paq variable to be set on the global scope.  This is set by adding the piwik code (shown in the example https://github.com/luisfarzati/angulartics/blob/master/samples/piwik.html).  If that is set properly angulartics will look for that _paq variable and add events to it.

I feel like I may not be answering your question fully, so maybe some example code of your problem might help in my understanding.

**Comment by Be-ngt-oH** [comment]
The piwik plugin currently uses a global variable which is inserted and configured by the tracking code snippet. It's very easy to do the very same configuration within the plugin which would render the tracking code obsolete. That could be a very clean solution (I don't suggest to add the unmodified tracking code anyway).

Is there already a standard way to configure angulartics plugins?

**Comment by postalservice14** [comment]
Currently, the way to configure the piwik plugin is to use the piwik snippet.  Yes, you might be able to add that in the plugin, but if the snippet changes, then the plugin breaks until someone updates it.  IMO, I prefer to put in the snippet on the index.html and declare it that way.  This is the same way the google analytics plugin works as well.

The current standard way to configure the plugin is to use the sample that I mentioned before. (of course changing the site ID and the URL to point to your piwik instance.

I do agree, we could probably improve the documentation to explain this better.

**Comment by ProLoser** [comment]
I'm going to close this issue for the above reasons stated. I will create a new issue to add clear documentation that you are expected to add the snippet yourself to all implementations. However, I do think there might very well be a possibility of removing the reliance on a global variable if it's not required by the piwik lib itself.
