### ISSUE TITLE
Feature: Exception Tracking

### ISSUE THREAD

**Issue by madvas** [angulartics/angulartics#272]
Hi,

It would be greatly helpful if we could track exceptions with Google Analytics as specified here https://developers.google.com/analytics/devguides/collection/analyticsjs/exceptions

I mean as there are methods `eventTrack` and `pageTrack` there could be another one `exceptionTrack` , which would send such requests to GA: 
`ga('send', 'exception', {
  'exDescription': 'DatabaseError',
  'exFatal': false
});`

Thank you very much

**Comment by luisfarzati** [comment]
This may be a good idea. Please submit a PR for discussion.

**Comment by luisfarzati** [comment]
I renamed this and let's agree that this shouldn't be vendor-specific but actually in the core.

**Comment by luisfarzati** [comment]
#313 implements this.
