### ISSUE TITLE
Add cdn info

### ISSUE THREAD

**Issue by PeterDaveHello** [angulartics/angulartics#275]
Hi @luisfarzati,

I'm Peter from cdnjs.com,

I wonder if you would like to add cdn info in the readme or the website?

This is the page we provide cdn for angulartics - https://cdnjs.com/libraries/angulartics

BTW: You can also use our service for your website to speedup the loading, also easier to maintain the src.

Thanks!

**Comment by luisfarzati** [comment]
Hi @PeterDaveHello, sure I'll do. Thanks! Please note that we are moving the plugins off the core and into their own repo, see https://github.com/angulartics/angulartics-google-analytics.

The rest of the plugins will be moved during the next few weeks.

**Comment by timelf123** [comment]
@PeterDaveHello I can't get cdnjs to pick up the latest angulartics versions. the last tag on there is 0.20.1 and https://cdnjs.com/libraries/angulartics/1.0.0 is a 404

**Comment by PeterDaveHello** [comment]
@timelf123 because this repo has been moved to angulartics, I will fix it.

**Comment by PeterDaveHello** [comment]
Looks good now @timelf123 @luisfarzati

**Comment by timelf123** [comment]
Awesome thanks @PeterDaveHello !

**Comment by PeterDaveHello** [comment]
@timelf123 is it available on readme or website now? I didn't see it.
