### ISSUE TITLE
minor issue: some .js files are missing license headers

### ISSUE THREAD

**Issue by ktiedt** [angulartics/angulartics#378]
As stated, minor, we run license checks for third party code and our compiler complains about ~4 or so files, I'll have to go back to get the list, but I was hesitant to submit a PR for this since some of the files are contributed by others, and such the license block reads a bit different (giving credit where it is due obviously). It wasnt immediately obvious if this was the case for these files.

**Comment by luisfarzati** [comment]
Please check out the list and let me know. Anyway, we are [moving the plugins into their own repo](https://github.com/luisfarzati/angulartics/issues/377#issuecomment-122460213) and I'm removing those license headers in the files. I put contribution credits in package.json and probably will do the same in the LICENSE file, but no longer in source files.

**Comment by timelf123** [comment]
Closing, please reopen or file a new issue if needed
