### ISSUE TITLE
Export angular module name

### ISSUE THREAD

**Issue by kentcdodds** [angulartics/angulartics#388]
As described [here](https://medium.com/@kentcdodds/how-to-distribute-your-angularjs-module-e04d4dd58ddc) :-) Makes it easier to consume the module.

**Comment by lunks** [comment]
PRs are welcome. :)

**Comment by luisfarzati** [comment]
Yes, this is planned, thanks! We'll do it when we move Angulartics to the new org. Or also you can submit a PR to get it early if you wish :)

**Comment by luisfarzati** [comment]
@kentcdodds, this will happen soon now that we have Angulartics under the new org.

**Comment by kentcdodds** [comment]
:+1:

**Comment by timelf123** [comment]
We aren't exporting things for ES5 at this time, but we did add an ES6 module here: https://github.com/angulartics/angulartics/blob/master/src/index.js

I'd welcome an ES5 solution as a PR

**Comment by nickcmaynard** [comment]
@luisfarzati Any advance on exporting the angular module name?  Is this now effectively done, or is something pending?  I'd like to know if I can require() this yet...

**Comment by timelf123** [comment]
It is exported https://github.com/angulartics/angulartics/blob/master/src/index.js#L2
