### ISSUE TITLE
Ability to add handlers after the config stage

### ISSUE THREAD

**Issue by aheuermann** [angulartics/angulartics#397]
We use a angular service to handle track events with angulartics.  Right now the way we handle adding the track handler is a little janky. 
```js
angular.module("app", [])
  .config(analyticsConfig);

analyticsConfig.$inject = ['$analyticsProvider'];
function analyticsConfig ($analyticsProvider) {
	function track (event, properties, options, callback) {
		getAppInjector().invoke(['reportingService', function track (reportingService) {
			reportingService.track(event, properties);
		}]);
	}
	$analyticsProvider.registerEventTrack(track);
}

function getAppInjector () {
	return angular.element(document.body).injector();
}
```

Would you be open to a PR that would add the ability to add handlers after config or is there another recommended way of doing this?

**Comment by ProLoser** [comment]
I'm so very confused. Your `reportingService` can't register the event itself?

**Comment by ProLoser** [comment]
Sorry I am just not following, what's wrong with forming your service the same way all the others are done?

**Comment by timelf123** [comment]
Closing, please reopen or file a new issue if needed
