### ISSUE TITLE
Useless function?

### ISSUE THREAD

**Issue by ProLoser** [angulartics/angulartics#402]
What does this even do?
https://github.com/luisfarzati/angulartics/blob/master/src/angulartics.js#L227-L230

It returns the same result in either situation

**Comment by luisfarzati** [comment]
Hmm that seems pretty stupid. Maybe I was thinking in other inferences (besides isCommand) but then I forgot. What's certain is that this code never had a code review by anyone, you seem the first one to spot some fringe stuff in it. Thanks for caring!

**Comment by lunks** [comment]
Feel free to do this proposals over PRs if you feel like to, @ProLoser.
It seems we can just replace https://github.com/luisfarzati/angulartics/blob/master/src/angulartics.js#L254 with `|| 'click'.
