### ISSUE TITLE
Move back to Gitter

### ISSUE THREAD

**Issue by ProLoser** [angulartics/angulartics#404]
I seriously don't feel like registering for MORE slacks. I don't know why we need it for such a small project.

**Comment by luisfarzati** [comment]
+1 to adding a more standard way for community chat. I just renamed the title and [configured IRC gateway in Slack]((https://slack.zendesk.com/hc/en-us/articles/201727913-Connecting-to-Slack-over-IRC-and-XMPP).

**Comment by luisfarzati** [comment]
It's worth noting that you need to register on Slack anyway... but the same happens with Gitter, right?

Maybe a fully independent IRC channel in freenode or something?

**Comment by ProLoser** [comment]
The key difference is you register once for Gitter, while on Slack you register for every single slack, and it seems silly to register for a chat room (one that I must keep activated mind you) with only ~20 people.

**Comment by luisfarzati** [comment]
That makes sense. Ok, @timelf123 created a Gitter at a moment, although it was for luisfarzati/angulartics so I don't think that'll be reusable.

**Comment by timelf123** [comment]
New Gitter is up

https://gitter.im/angulartics
