### ISSUE TITLE
Please make me a co-owner of the angulartics org

### ISSUE THREAD

**Issue by ProLoser** [angulartics/angulartics#405]
It seems I'm the only one who's relatively active on Github these days, as none of the other owners have been active within the past month, and issues on this lib are piling up.

I'd like to once and for all relocate this repo over to the angulartics org (I'm frankly a little confused why it hasn't been done already). At the very least a fork could be made where development could continue.

I've also identified after spelunking through the source some glaring performance problems with the angular-centric code and would like to clean up these problems vs starting an alternative library under the AngularUI namespace which may at this point be a bit of a hassle considering the large number of integrations this project already has.

**Comment by luisfarzati** [comment]
Hi @ProLoser. I wanted to make sure [the rest of the plugins were migrated to the new Org](https://github.com/luisfarzati/angulartics/issues/390) before moving the core. But this doesn't seem to be happen any soon. I started moving some of them and doing some organizational improvements and clean up but got swamped again with other stuff until October. @lunks and @timelf123 may have also too many things on their plate as well.

I'm glad you want to join the project! I'll give you access right away. There's a lot of room for improvement, specially in the core codebase, considering this was one my first Angular projects back in the v1.1 days. I'm sure there newbie stuff that can be improved, as well as code that can be upgraded using newer Angular features.

Welcome!

**Comment by ProLoser** [comment]
Thanks @luisfarzati!

**Comment by ProLoser** [comment]
@luisfarzati I am kinda curious, how come you didn't just transfer ownership of this repo to the org? No data would be lost, you'd just have to update the URLs and Github does this provisionally for you to some degree too.

**Comment by ProLoser** [comment]
@luisfarzati I realize this might be pushing things, but is there any chance I could get administrative privilege to this repo? Unless you wish to retain the primary fork under your namespace, it will enable me to try and make other updates as I move things over (such as transferring ownership eventually and/or updating the repo URL to point to the new webpages)

**Comment by ProLoser** [comment]
After a little bit of thought, here's what I'd like to do:

1. Transfer ownership of this repo over to the org
2. Fork back to this namespace so that no URLs break
3. Continue HEAD development up-stream (on the org repo)
4. Update all github and package distribution URLs to point to new repo

This will create a good transitional period with 0 downtime and will help us avoid holding off on development. I've done this several times [with](https://github.com/ProLoser/CakePHP-Wizard) [other](https://github.com/ProLoser/AnythingSlider) [projects](https://github.com/ProLoser/AngularJS-ORM)

**Comment by luisfarzati** [comment]
I'm not sure. I just didn't want to have Angulartics under the new Org until all plugins were transferred. But I'm not sure doing that is of any real benefit.

So, how do we do this? I already gave you collaborator access but that's not enough I guess. Should I transfer the repo to the new org? Or to you?

**Comment by ProLoser** [comment]
Transfer the repo to the new org. Once it's there, you should hit the fork button which will pull an up-to-date snapshot back to your own namespace but all fork references will point upstream to the org. Then we can resume development under the org

**Comment by luisfarzati** [comment]
Ok, done!
