### ISSUE TITLE
Drop NuGet support

### ISSUE THREAD

**Issue by luisfarzati** [angulartics/angulartics#407]
Last call for anyone interested in taking ownership of NuGet packaging. We'll drop this soon.

**Comment by ProLoser** [comment]
No idea what it even is personally :/

**Comment by luisfarzati** [comment]
Yet Another Package Manager, very popular in the Microsoft .NET community.

**Comment by brettjacobson** [comment]
:+1:
As a .NET guy, I can confirm that many shops are moving towards using Bower for client side packages, and limiting use of NuGet to .NET packages.  The latest Visual Studio tooling is treating Bower as a first class citizen, so devs on the latest VS would barely notice (and likely not care) about the package source being NuGet vs Bower.

**Comment by timelf123** [comment]
Thanks for the feedback @brettjacobson 

Closed by https://github.com/angulartics/angulartics/commit/a07cfd7d08a067568a18a4a28ed40aa65441be99 - will remove nuget directory in next release
