### ISSUE TITLE
Analytics call delays load event

### ISSUE THREAD

**Issue by atd** [angulartics/angulartics#412]
Page load event is delayed by several seconds due to the call to the analytics server.

I expected the call to be asynchronous. Is this the expected behavior or am I missing something?

![image](https://cloud.githubusercontent.com/assets/26228/10131695/675a1f8c-65d2-11e5-8424-aaf4130039c7.png)

**Comment by ProLoser** [comment]
Not the responsibility of our codebase, you'll have to look at piwik.
