### ISSUE TITLE
Unable to fork or comment on issues in the angulartics-google-analytics repository

### ISSUE THREAD

**Issue by Emeegeemee** [angulartics/angulartics#414]
Is anyone else getting errors trying to fork or comment on issues in the angulartics-google-analytics repository?

**Comment by ProLoser** [comment]
I don't see this issue. Can you post a screenshot or something?

**Comment by Emeegeemee** [comment]
![screenshot from 2015-09-29 11-19-01](https://cloud.githubusercontent.com/assets/4241156/10174031/6a31e530-669c-11e5-8068-857cb8484c96.png)
![screenshot from 2015-09-29 11-20-10](https://cloud.githubusercontent.com/assets/4241156/10174032/6a42b928-669c-11e5-92d8-b6fb213f0018.png)

In the first picture when I click comment I get this error.
In the second picture clicking the fork button open the model but nothing ever happens.

**Comment by ProLoser** [comment]
Submit a request to Github, we don't have control over this
