### ISSUE TITLE
Adding ECommerce Support to Google Plugin

### ISSUE THREAD

**Issue by pfried** [angulartics/angulartics#42]
As we need some Ecommerce in our company i would like to suggest an approach to do this.

I added some functionality to the google analytics plugin which enables some Event namespacing without the need to alter the angulartics.js

https://github.com/pfried/angulartics

I followed the way Google uses for ECommerce in analytics.js https://developers.google.com/analytics/devguides/collection/analyticsjs/ecommerce

For example i can add an item by  calling `angulartics.eventTrack('ecommerce:addItem', {...})` using a delimitor in the event name.

I implemented the complete functionality regarding ECommerce in `analytics.js`. I wrote some tests to prove the compatibility and ensure it calls Google Analytics correctly.

It is only a draft for the moment and i will integrate it with our shop in the next week. Also i want to mention that there is no support for the "old" Google Analytics (_gaq) as i do not need it, but it would be easy to add.

Any thoughts on this? I first thought about adding this on a higher level but soon realized adding a third event queue is not the way to go.

**Comment by derekakers** [comment]
What's the status on this?  We also need eCommerce transaction tracking and are using Angulartics.  Did anything like this get added?

**Comment by yaronguez** [comment]
@luisfarzati I didn't quite understand your comment.  Does Angulartics support e-commerce? Is another plugin required?

**Comment by timelf123** [comment]
The planned 1.0.X version was scrapped as @luisfarzati does not have time to rewrite. At the moment, there are no GA ecommerce features, but we are always open to review PR for vendor plugins

**Comment by yaronguez** [comment]
Thanks for the update.

------------------------------------------------
Yaron Guez
Software Architect / Developer
(781) 767-7434
