### ISSUE TITLE
Link to angulartics-ga is broken on http://angulartics.github.io/

### ISSUE THREAD

**Issue by hakib** [angulartics/angulartics#422]
The link currently poiny [here](https://github.com/angulartics/angulartics/blob/master/src/angulartics-ga.js). It's also not very clear from the page that it's neccessary to install an [additional package](https://github.com/angulartics/angulartics-google-analytics/blob/master/lib/angulartics-google-analytics.js) for ga. All other vendors has their plugin as part of angulartics but not ga.

Maybe I got it all wrong but I got confused (still am).

**Comment by awebdeveloper** [comment]
even i too noticed the second point

**Comment by timelf123** [comment]
Fixed the link in https://github.com/angulartics/angulartics.github.io/commit/c433f15379dbfb77368bf43823d1d01aa9bed703 thanks
