### ISSUE TITLE
Angular2 support planned?

### ISSUE THREAD

**Issue by pgrm** [angulartics/angulartics#427]
Hi, this has been a very useful package for me so far and I'm currently experimenting with an Angular2 app. Any plans to support Angular2?

Unfortunately I don't trust my JavaScript skills enough to do that, but if you'd be interested in it, I could try implementing the support, while rewriting it to typescript.

**Comment by JonnyBGod** [comment]
+1

**Comment by timelf123** [comment]
I haven't looked into Angular 2 very much yet. I know there are ways to use Angular 2 code in an Angular 1 app (ng-upgrade, ng-forward), but don't want people to have to include an extra lib to use Angulartics on v1.

Perhaps this should be done in a branch for now? Thoughts @angulartics/core

**Comment by skovmand** [comment]
+1

**Comment by JonnyBGod** [comment]
@timelf123 I believe it is best to do a all new repository for say "angular2-angulatics" as the current code base is very tightly connected to angular1. For angular2 most of the code can be redone in plain javascript classes. I am happy to help setting up the project and doing the core and GA implementations. Don't have the time for all other integrations though.

As for angular1 with the new component router, this could be done on a branch for now. It is difficult to know if this is even needed as it depends if users will go straight to angular2 or will try angular1 with new router... Probably best to invest on consulting the community to better understand if there any need for this feature.

**Comment by JonnyBGod** [comment]
quick example if you want to do some testing to track route changes on angular2.

```
import {Injectable} from 'angular2/core';
import {Router, RouterLink} from 'angular2/router';

@Injectable()
export class StatusListener {
	constructor(
		router: Router,
		status: status
	) {
		router.subscribe((route) => {
			console.log(route);
			console.log(router.recognize(route));
		});
	}
}
```

**Comment by timelf123** [comment]
Awesome work @JonnyBGod!

[UI-router 1.0 alpha](https://github.com/angular-ui/ui-router/releases/tag/1.0.0alpha0) came out recently and their goal for the next release is to support both Angular 1 and 2. Is it possible to do this in the same repo? I have zero Angular 2 experience.

There is a repo created https://github.com/angulartics/angulartics2 - feel free to contribute there

**Comment by JonnyBGod** [comment]
Will do. Need some time to study the current implementation better and understand all needs.

As for hybrid version, it might be possible. The routers are very similar in functionality and from what I saw probably about 70% of code is similar. This might be possible with a simple wrapper for angular1 version but needs further study.

I would focus on angular2 for now. The benefits from moving to angular2 are too good to just stay in angular1 and save a few weeks of work. (that my opinion) So we should provide an easy way to do so by supporting angular2 as soon as possible.

Do you have any idea of what are the most used integrations?

**Comment by timelf123** [comment]
A hybrid version would be amazing but I agree that it doesn't hurt to get out a purely Angular 2 version in the mean time.

I would guess google analytics, mixpanel, kissmetrics, and segment are the most used plugins

**Comment by JonnyBGod** [comment]
I just release an initial implementation of angulartics for angular2 https://github.com/angulartics/angulartics2

Lets bring al angular2 discussion to the new repo.

**Comment by pgrm** [comment]
:+1:

**Comment by ilhemboulaabi** [comment]
Is angulartics2 compatible with angular1.6

OR

Is angulartics compatible with angular2

Because I'm currently working with angular 1.6 and I plan to migrate to angular2 in the future, and I'm searching for a solution that is compatible with both

**Comment by timelf123** [comment]
You will have to manually migrate
