### ISSUE TITLE
Piwik Minified version doesn't contain `setCustomVariable`

### ISSUE THREAD

**Issue by matejkramny** [angulartics/angulartics#428]
Aside from this issue, I found it confusing to integrate everything due to lack of documentation.

Thanks

**Comment by timelf123** [comment]
What version of Angulartics are you using? I see the setCustomVariable code in the lastest minified file

Documentation could be improved -- what specifically did you have problems with?

**Comment by matejkramny** [comment]
I was using the latest version. Let me see if i can dig something out

With the documentation, I was initially really confused how to set up the
trackers I use (piwik and gosquared).
It doesnt say anywhere what you need to do for each tracker, neither does
it say which api methods are exposed by angulartics.

Process is:
1. Download angulartics
2. Download plugins
3. Download vendor plugins
4. Set up tracking per vendor

On Mon, 30 Nov 2015 at 20:33, Tim Elfelt <notifications@github.com> wrote:

> What version of Angulartics are you using? I see the setCustomVariable
> code in the lastest minified file
>
> Documentation could be improved -- what specifically did you have problems
> with?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angulartics/angulartics/issues/428#issuecomment-160753425>
> .
>
-- 
Matej Kramny

**Comment by timelf123** [comment]
Agree that our docs could use some love. Closing this as Piwik seems to have the function you needed. Feel free to re-open if this is not the case
