### ISSUE TITLE
support dotJEM angular router

### ISSUE THREAD

**Issue by mcampster** [angulartics/angulartics#432]
We use state based routing with dotJEM. As such, when we load a new state, the location changes, the route changes and the state changes. This means all the success events are fired and the page track is sent twice.

Is this how it is supposed to work?

**Comment by timelf123** [comment]
You are using `ui-router` only, or `ui-router` AND the ng router?

**Comment by mcampster** [comment]
Actually, I'm using dot jem router. But surely that should not matter - it fires the same events as ui-router. Angulartics seems to listen to both route change and state change events. Most applications that use state based 'routing' will also use the $router solely for the 'otherwise' scenario where you can set a default state. So if this is the case, angulartics will always track each event twice.

**Comment by mcampster** [comment]
I've just taken a look at the ui-router and it looks like they are using $urlRouterProvider for the otherwise instead of $route as we do. So that would explain it. 

However, I still don't think that any location change should be tracked twice regardless of if you are using 1, 2 or 3 different routing providers.

**Comment by timelf123** [comment]
Can you add a jsfiddle / jsbin example so I can play around a bit?

Angulartics listens for `$routeChangeSuccess` and `$stateChangeSuccess` -and also `$locationChangeSuccess` when `noRoutesOrStates` is set (eg on a static page that has no routing)

**Comment by timelf123** [comment]
@mcampster did you figure this issue out? If not, please post a jsfiddle example so I can debug

**Comment by Emeegeemee** [comment]
I started looking into this, it looks like the dotJEM router uses both the $routeChangeSuccess and $stateChangeSuccess events as well as registers $route and $state services. So it would indeed setup a listener for each event in the [angulartics.js code](https://github.com/angulartics/angulartics/blob/d9788e73f8c483a1954b80a23ba4d7e9e3e71da8/src/angulartics.js#L204-L222). This is an unfortunate accident since usually you won't have both a $state and $route service when assuming that an application uses either the ui-router or ngRoute.

**Comment by Emeegeemee** [comment]
The fix could simply be adding else to the $state service check [here](https://github.com/angulartics/angulartics/blob/d9788e73f8c483a1954b80a23ba4d7e9e3e71da8/src/angulartics.js#L216), but that assumes you always want to use the $routeChangeSuccess as the tracking event in the dotJEM router and I'm not familiar with it to make that decision. So I would have to ask @mcampster whether or not that would work.

**Comment by mcampster** [comment]
Hi - sorry. I added this bug then deserted you for Xmas! 

Dotjem router separates routes and states, although typically you would map a state to a given route. In a classic use case, the location would change , which would trigger the route change event, which would map to a state change event. It would always be in this order. 

Anyone using dotjem router is probably not using it for the route change events, but the state change. The route change is more there for backwards compatibility.

My suggestion would be to make the tracking more configurable so you do not need to know about the implementations of each router. e.g. instead of autoTrackVirtualPages, you could have trackRoutes and trackStates. It could default to one and not the other, but allows the developer to configure it how they want. If you were tracking states, you probably would want the state name and not the url tracked as it is easier to read.
