### ISSUE TITLE
Feature : offline mode

### ISSUE THREAD

**Issue by younes200** [angulartics/angulartics#433]
Hi,
It would be greatly helpful if we could have a offline mode with Google Analytics similar to : https://github.com/revolunet/angular-google-analytics#offline-mode
Thanks

**Comment by timtos** [comment]
Any updates on this?

**Comment by sbrown345** [comment]
Is there a workaround? 

For some like GA it seems like I can check the hostname and pass in "none" 
e.g. ` ga('create', window.location.hostname === 'localhost' ? 'none' : 'UA-xxxxxxxx');`

But for woopra I'm getting lots of 404 errors if I do that.

**Comment by timelf123** [comment]
@sbrown345 you could wrap your whole woopra block in an if statement if you don't want to init it.

As always, PR welcomed. @younes200 We aren't managing the script tag like the package linked does `Analytics.createAnalyticsScriptTag();` so I think this is best left to your implementation
