### ISSUE TITLE
Semantic Versioning

### ISSUE THREAD

**Issue by esetnik** [angulartics/angulartics#438]
The latest release is labeled 0.2.3, this is semantically behind 0.20.2 which causes bower to incorrectly list 0.20.2 as the latest version. My suggestion to avoid this issue is to release 1.0.0 as the first stable version.

**Comment by timelf123** [comment]
My bad! I'll release something after the holidays!

**Comment by esetnik** [comment]
No problem thanks for the sweet plugin

**Comment by timelf123** [comment]
the package.json and bower.json files had the right tag version - I removed the erroneous tag and pushed the correct 0.20.3. Planning on pushing 1.0.0 later this afternoon. 

Thanks for the catch!

**Comment by esetnik** [comment]
Fantastic! thanks for the quick fix.

**Comment by timelf123** [comment]
1.0.0 is out :)
