### ISSUE TITLE
google analytics plugin missing?

### ISSUE THREAD

**Issue by szimano** [angulartics/angulartics#440]
Hi,

I am using angulartics version 1.0.2 and i do not see the `angulartics-ga.js` plugin inside. There are two cordova plugins - `angulartics-ga-cordova.js` and `angulartics-ga-cordova-google-analytics-plugin.js` - is that intentional?

Thanks,

**Comment by tydanielson** [comment]
The plugins are moving to their own repos, you can find the ga one here.
https://github.com/angulartics/angulartics-google-analytics

**Comment by szimano** [comment]
ah i got confused, cause i tried to add it but it showed me that it depends on some ancient version of angulartics (~0.20). Adding `angulartics/angulartics-google-analytics#master` did the trick :)

Thanks, and happy new year!

**Comment by timelf123** [comment]
Sorry, I still need to go through all the plugins and make sure they are referring to `Angulartics ^1.0.0`
