### ISSUE TITLE
Multiple installations of google tag manager detected

### ISSUE THREAD

**Issue by bdairy** [angulartics/angulartics#442]
Hi there, I am using GTM account that has a tag for google analytics inside it, I followed your steps and worked perfectly as I hope.. but I have an issue with duplicating the tag of GTM with every page view.. please note that I am not doing any special calls for page views,, I am just using the angularitics google analytics default page view.
I am using google tag assistant check the screen shot,,, that helped me to figure out the duplicates,,  I inspected the source and the tag is not beeing duplicated.,,, I just want to confirm if that is an issue or not..
Thanks
![screen shot 2016-01-11 at 6 41 56 pm](https://cloud.githubusercontent.com/assets/10797121/12236551/ef6a2ee4-b893-11e5-8649-131a17f3767f.jpg)

**Comment by timelf123** [comment]
ping @angulartics/google

**Comment by cbmono** [comment]
+1

**Comment by DanWilkerson** [comment]
Tag Assistant is a little buggy. I've seen this many times before (in a wide variety of stacks/contexts). Bottom line, this is not caused by Angulartics. You can verify this by inspecting the dataLayer manually ('dataLayer' in console), checking the source, and checking the hits that come in to GA.

**Comment by bdairy** [comment]
It has been a while, and the tag manager still duplicates,, but the results reflects that everything is working fine, and no duplicates are happening,,, So I guess it is a google tag manager bug.

**Comment by Dharmoslap** [comment]
Happens to me as well.

**Comment by DanWilkerson** [comment]
Yes, this is a Google Tag Assistant bug. I believe this issue can be closed.
