### ISSUE TITLE
Duplicate ga-cordova plugins

### ISSUE THREAD

**Issue by Meekohi** [angulartics/angulartics#443]
`src/angulartics-ga-cordova.js` and `src/angulartics-ga-cordova-google-analytics-plugin.js` are basically the same file. Which one should we be using?

**Comment by timelf123** [comment]
src/angulartics-ga-cordova-google-analytics-plugin.js uses https://github.com/danwilson/google-analytics-plugin it appears. Sorry for the confusion! Feel free to submit a PR with better documentation
