### ISSUE TITLE
How to use more the one vendor at the same time?

### ISSUE THREAD

**Issue by pedrommuller** [angulartics/angulartics#446]
I'd like to use two different vendors and track basically the same information / events for both of them at the same time.

**Comment by shairez** [comment]
By looking at the source code it looks like it was designed to support multiple vendors at once.

**Comment by timelf123** [comment]
`var yourApp = angular.module('YourApp', ['angulartics', 'angulartics.google.analytics', 'angulartics.your.module'])`
