### ISSUE TITLE
angular-ui-router deprecating state events

### ISSUE THREAD

**Issue by CrispyBacon12** [angulartics/angulartics#454]
Page views will no longer trigger when used with ui-router@1.0.0, since they have [disabled state events by default](https://github.com/angular-ui/ui-router/releases/tag/1.0.0alpha0). 

It seems as though angulartics [depends on these events](https://github.com/angulartics/angulartics/blob/master/src/angulartics.js#L240)? "$state" is still in the injector, so it won't fall back to using $locationChangeSuccess.

State events are being replaced with transition hooks. This can be implemented much the same way as the existing $stateChangeSuccess listener, based off `$injector.has("$transitions")`. Are there any plans to support this? I can submit a PR.

**Comment by timelf123** [comment]
Thanks for the heads up! There are no plans in the works. I'd be happy to review a PR with tests :)

**Comment by timelf123** [comment]
Leaving this open as the merged solution is not working with `ui-router` 1.0.0-beta https://github.com/angulartics/angulartics/issues/504

**Comment by CrispyBacon12** [comment]
It looks as though since my merge, there's been a subsequent change (78ef78858a3480ac5c988bb1a8007960c6117824) which added inline annotations to the onSuccess hook.

However, angular-ui-router has stopped treating the hooks as injectable which is what's causing these issues: [BC-BREAK: Transition Hooks are no longer injected (onBefore/onStart/onExit/onRetain/onEnter/onFinish/onSuccess/onError)](https://github.com/angular-ui/ui-router/commit/ca45957901d53a77f69074d15ea87baf1b78a48c)

I'll submit a PR to un-do the inline annotation.

**Comment by timelf123** [comment]
@CrispyBacon12 thanks for the detailed explanation. Closing as fixed in #512
