### ISSUE TITLE
uBlock Origin Ad-Blocker

### ISSUE THREAD

**Issue by romin4you** [angulartics/angulartics#465]
uBlock is blocking angulartics. Tested and confirmed!!!

**Comment by janbomber** [comment]
rename the file

**Comment by philhudson91** [comment]
+1 

We work with Bower so ideally need it renamed in the Bower package.

Also, we should consider some kind of graceful handling for situations when this module cannot be loaded.

**Comment by jdegger** [comment]
Renaming it is useless, they will just (rightfully) block it again. It should not brick the application though.

**Comment by philhudson91** [comment]
I'm going to try to implement some kind of graceful lazy loading strategy for Angular modules as an alternative :) @jdegger

**Comment by timelf123** [comment]
Bricking the application due to a missing Angular module is outside of the scope of Angulartics. 

Solution is to bundle the file with other assets. NOTE: ublock will likely block most http calls to the analytics providers too, but at least the app will not brick
