### ISSUE TITLE
Uncaught TypeError: $exceptionHandler is not a function

### ISSUE THREAD

**Issue by darkange69** [angulartics/angulartics#483]
function exceptionTrack($provide) {
  $provide.decorator('$exceptionHandler', ['$delegate', '$injector', function ($delegate, $injector) {
    var excTrack = function (error, cause) {
      var result = $delegate(error, cause);
      var $analytics = $injector.get('$analytics');
      if ($analytics.settings.trackExceptions) {
        $analytics.exceptionTrack(error, cause);
      }
      return result;
    }
  }]);
}

should be:

  function exceptionTrack($provide) {

    $provide.decorator('$exceptionHandler', ['$delegate', '$injector', function ($delegate, $injector) {
      return function (error, cause) {
        var result = $delegate(error, cause);
        var $analytics = $injector.get('$analytics');
        if ($analytics.settings.trackExceptions) {
          $analytics.exceptionTrack(error, cause);
        }
        return result;
      }
    }]);
  }

the missing return case 'Uncaught TypeError: $exceptionHandler is not a function' instead of the real exception when an exception is raised.

**Comment by darkange69** [comment]
this code seems to fix it:
$provide.decorator("$exceptionHandler", ['$delegate', '$injector',function ($delegate, $injector) {
      return function (exception, cause) {
        var result = $delegate(exception, cause);
        var $analytics = $injector.get('$analytics');
        if ($analytics.settings.trackExceptions) {
          $analytics.exceptionTrack(error, cause);
        }
        return result;
      }
    }]);

**Comment by timelf123** [comment]
Can you PR this please?
