### ISSUE TITLE
$analytics.eventTrack not firing ga events

### ISSUE THREAD

**Issue by abautist** [angulartics/angulartics#487]
I am trying to track an event on a <select> tag of a drop-down menu. If I use ````analytics-on```` in the html directly I am only able to track the click event and not the ````onchange```` event. To work around this, I have a function attached to an ng-change like so: `<select ng-change=“sortListView( )”>` and a controller based on the documentation:

`controller: function($scope, $analytics){
	$scope.sortListView = function( ) {
		[….]
		$analytics.eventTrack('testTag');
	};
}`

However, the event is not getting picked up by google analytics. Is there any additional implementation required for this to work in my angular app? Declarative event tracking works without a problem, only having issues with $analytics.

**Comment by timelf123** [comment]
Have you installed [angulartics/angulartics-google-analytics](https://github.com/angulartics/angulartics-google-analytics)?

**Comment by timelf123** [comment]
Please reopen if you still are experiencing issues
