### ISSUE TITLE
Module not available

### ISSUE THREAD

**Issue by jeffhuys** [angulartics/angulartics#489]
Hi, I've followed your instructions to install google-tag-manager angulartics: `bower install angulartics-google-tag-manager --save`. The scripts are included like this:

![screen shot 2016-06-24 at 11 51 55](https://cloud.githubusercontent.com/assets/2276233/16334627/5be6f864-3a02-11e6-8ef7-d02c9ca98f34.png)

But I get the following error:

![screen shot 2016-06-24 at 11 54 42](https://cloud.githubusercontent.com/assets/2276233/16334649/76611ed6-3a02-11e6-9256-dc0522a0d3cd.png)

What have I done wrong? Thanks for your help!

Edit: excuse me if this is not what you want to use issues for

**Comment by jeffhuys** [comment]
Please? 😢

**Comment by timelf123** [comment]
there is no `/lib/` folder, change `/lib/` -> `/src/`

see https://github.com/angulartics/angulartics/

**Comment by jeffhuys** [comment]
Thank you! I've migrated to TypeScript now, though, and it works awesomely.
