### ISSUE TITLE
Missing commits in 1.1.2 release

### ISSUE THREAD

**Issue by zwacky** [angulartics/angulartics#498]
hey there

I just checked that my merged into master PR #492 didn't make it to the 1.1.2 release. I might be missing something? In the meantime i'll use master.

Cheers

**Comment by timelf123** [comment]
Sorry about that, I'll cut a release next week. Feel free to ping me if I haven't gotten to it yet

**Comment by zwacky** [comment]
sounds good.

**Comment by zwacky** [comment]
@timelf123 ping!

**Comment by timelf123** [comment]
Thanks for the ping! Will try to publish today

**Comment by timelf123** [comment]
https://github.com/angulartics/angulartics/releases/tag/1.1.3
