### ISSUE TITLE
Question: how to defer sending pageview until a User ID is resolved?

### ISSUE THREAD

**Issue by chungconscious** [angulartics/angulartics#500]
Right now, pageview is being sent before a user ID is resolved. 

**The problem for our data** 
When users open a browser where a session was previously established, the first page view is erroneously recorded as a page view for a user without an account, i.e. new site visitor. 

This is skewing tracking of new visitors to the site. 

**Details**
Resolving the user ID looks like this: 
1) check cookies for user ID
2) if it exists, refresh the credentials with JWT in an http post call

The pageview is sent before #2 above is complete. 

Any advise would be much appreciated!

**Comment by timelf123** [comment]
[turn off auto pageview tracking](https://github.com/angulartics/angulartics/blob/master/README.md#playing-around), then send `$analytics.pageTrack()` call in the callback to **2** above (JWT in http post call)

**Comment by timelf123** [comment]
Please reopen if you still are experiencing issues
