### ISSUE TITLE
How set User-ID parameter? 

### ISSUE THREAD

**Issue by cawa-93** [angulartics/angulartics#501]
https://developers.google.com/analytics/devguides/collection/analyticsjs/cookies-user-id#user_id

**Comment by timelf123** [comment]
`$analytics.setUsername(username)`

**Comment by timelf123** [comment]
```
$analytics.setUserProperties(UserService.user._id, {
  name: UserService.user.name,
  username: UserService.user.username,
  email: UserService.user.email
})
```

**Comment by scne** [comment]
Nope! If I set $analytics as above, and using google analytics debugger, nothing userId is sent and into report I see only a generated userId value

**Comment by timelf123** [comment]
@scne you tried with both syntax `$analytics.setUserProperties(id)` and `$analytics.setUsername(id)`?

Which google analytics plugin are you using?

**Comment by scne** [comment]
Yes I do! I'm using angulartics.google.analytics latest version

**Comment by VikramTiwari** [comment]
@scne Were you able to find a solution to this?

**Comment by timelf123** [comment]
@VikramTiwari can you share some more information about your setup?

**Comment by VikramTiwari** [comment]
@timelf123 Nothing unusual. Just trying to set the value of userId, yet the value is autogenerated cookie id.
