### ISSUE TITLE
Issue with ui-router 1.0.0-beta.1

### ISSUE THREAD

**Issue by facultymatt** [angulartics/angulartics#504]
I have yet to investigate but wanted to leave a quick FYI 

- Breaking with ui-router 1.0.0-beta.1 https://github.com/angular-ui/ui-router
- rolling back to 1.0.0-alpha.5 does not break in same way
- Throws error `Swallowed exception during synchronous hook handler: TypeError: hookFn.call is not a function` on page view.

**Comment by timelf123** [comment]
Not on 1.0.0 yet, but when I installed a 1.0X flavor and ran the tests, everything related to `$transition` failed

https://github.com/angulartics/angulartics/pull/455/commits/543da16133a878715afc4432435dc9fd3a196a79

**Comment by stockholmux** [comment]
I had the same problem, my work around at the app level was to do this in `.run(...)`:

```
$transitions.onSuccess(true,function($transition$) {
  $analytics.pageTrack($transition$.router.urlRouter.location);
});
```

**Comment by Shabla** [comment]
Same here, had this error with angular-ui-router 1.0.0-beta.2 and angulartics 1.1.3:
`TypeError: eventHook.callback.call is not a function`.

It works with stockholmux's solution, you just also have to disable virtual page tracking in a config block
`$analyticsProvider.virtualPageviews(false);`

**Comment by timelf123** [comment]
Can someone test adding the shim angular module `ui.router.state.events` https://ui-router.github.io/docs/latest/modules/ng1_state_events.html to see if this helps?

**Comment by mcranston18** [comment]
@timelf123 Getting the same error using `ui-router 1.0.0-beta.2` and `angularitics 1.1.2` and can confirm loading in `ui.router.state.events` does not solve it.

What did work was @Shabla's solution, adding `$analyticsProvider.virtualPageviews(false);` to my module config.

**Comment by CrispyBacon12** [comment]
angular-ui-router@1.0.0-beta.2 includes a change to transition hooks, making them no longer injected (https://github.com/angular-ui/ui-router/commit/ca45957901d53a77f69074d15ea87baf1b78a48c). 

That's what's causing these issues, and it's why these fixes that override the onSuccess handler with a non-annontated function are making the errors go away.

PR: https://github.com/angulartics/angulartics/pull/512

**Comment by timelf123** [comment]
Thanks! Landed in https://github.com/angulartics/angulartics/commit/b3e75184a2391f14d577d48f29e792965478d5d5 and tagged as angulartics@1.2.1
