### ISSUE TITLE
jasmine tests breaking after including angulartics

### ISSUE THREAD

**Issue by nandkv** [angulartics/angulartics#508]
I have reviewed couple of issues https://github.com/angulartics/angulartics/issues/181 and none of the solutions seems to make the test pass for Jasmine.

Here are the versions with angular 1.5.8 as resoluton:
angulartics-google-analytics#0.2.1 bower_components/angulartics-google-analytics
└── angulartics#1.1.3

angulartics#1.1.3 bower_components/angulartics
├── SHA-1#0.1.1
└── angular#1.5.8

**Comment by timelf123** [comment]
Could be similar to https://github.com/tom-james-watson/phantomjs-polyfill

**Comment by nandkv** [comment]
No response to this, so closing this issue.
