### ISSUE TITLE
Error loading angulartics module using JS 'concat' and 'uglify'

### ISSUE THREAD

**Issue by RodolpheNivelet** [angulartics/angulartics#516]
Hello,

I'm using bower and grunt on my project, and all my vendors including :
- angular 1.5.8
- angular-ui-router 0.3.1
- angulartics 1.2.0
- angulartics-google-analytics 0.3.0
- others....
are compiled into one file and uglified so they take as less space as possible.

I never had problem with any of my dependencies before. With angulartics I get this JS error :
`Uncaught Error: [$injector:modulerr] Failed to instantiate module hubFrontApp due to:
Error: [$injector:modulerr] Failed to instantiate module angulartics due to:
Error: [$injector:nomod] Module 'angulartics' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.`

This error happen only if files are concatened.

Anyone have experienced this error before ?

**Comment by timelf123** [comment]
You mentioned you files are uglified too, does the problem persist if uglify is turned off, or you add `mangle: false` to the uglify config?

**Comment by RodolpheNivelet** [comment]
I actually tried to put this param, and I finally repaired the issue by putting the dependency higher in the dependencies object of bower.json
