### ISSUE TITLE
sending beacon before the controller is executed

### ISSUE THREAD

**Issue by anantanandgupta** [angulartics/angulartics#535]
I am trying to use this extension with an application where the page title changes with each view using a service. The page title is set via controller, but the beacon is sent before that. I have not found any why to configure beacon to be sent once the complete UI is rendered.

To overcome as of now i am calling the service from resolve. but there is an issue in there too ... resolve is not called every time if the value is already resolved. so the best place to control the page title is through the controller only. I am using ui-route module for my routes.

Please provide a solution for me. I would really like to use this module in many of my applications i am currently working on. here is the code for my provider:

```JavaScript
(function () {
    'use strict';

    angular.module('utility')
        .provider('page', function () {
            var pageTitle = 'Home';
            var siteTitle = 'MySite';
            var pageTitleOnly = false;

            var setSiteTitle = function (newTitle) {
                siteTitle = newTitle;
            }

            var setPageTitle = function (newTitle) {
                pageTitle = newTitle;
            }

            this.setSiteTitle = setSiteTitle;
            this.setPageTitle = setPageTitle;
            this.pageTitleOnly = pageTitleOnly;

            this.$get = [function () {
                var oServiceInterface = {};

                oServiceInterface.setPageTitle = setPageTitle;
                oServiceInterface.getTitle = function() {
                    if(pageTitleOnly) {
                        return pageTitle;
                    } else {
                        return siteTitle + ' - ' + pageTitle;
                    }
                }

                return oServiceInterface;
            }];
        });
}());
```
and here is how my sample state looks like:
```JavaScript
state('user.repos', {
    url: '/Repositories',
    resolve: {
        repositories: ['gitService', '$stateParams', function (gitService, $stateParams) {
            return gitService.getUserRepositories($stateParams.login);
        }],
        pageTitle: ['page', function (page) {
            page.setPageTitle('User Repositories');
            return page.getTitle();
        }]
    },
    views: {
        'section@user': {
            templateUrl: function () {
                var url = 'Views/User/Repositories/';
                console.log('loading template : ' + url);
                return url;
            },
            controller: ['$scope', 'repositories', function ($scope, repositories) {
                console.log('Repositories Controller');
                $scope.repositories = repositories.data;
            }]
        }
    }
})
```

in above code `pageTitle` property in resolve object is invoking the `page.setPageTitle('User Repositories')` method and below here it is used in the view of main html page
```html
<head>
    <title>{{page.getTitle()}}</title>
</head>
```

If I call the service method in the controller to set the title, it changes the title but, the beacon has been invoked before that, while capturing the previous page title. Please let me know in case you need more details on this.

Thanks,
Anant Anand Gupta
**[About Me](https://about.me/anantanandgupta)** | **[GitHub Profile](https://github.com/anantanandgupta)**

**Comment by timelf123** [comment]
This is one way:
1. turn off auto pageview tracking
2. send an event when the title has changed
3. add a listener 
```
  $rootScope.$on('$titleChangeSuccess', function(event, route) {
    $analytics.pageTrack($location.path());
  });
```

**Comment by anantanandgupta** [comment]
Thanks @timelf123

**Comment by timelf123** [comment]
No problem, marking as solved
