### ISSUE TITLE
ngBindHtml with analytics-on did not work

### ISSUE THREAD

**Issue by donamk** [angulartics/angulartics#537]
Hello,

I think it may not a bug but I have no idea how to make analytics-on to work.

```
// controller
$scope.testHtml = "<a href='url' analytics-on>link</a>"

// html
<div ng-bind-html="testHtml"></div>
```
this use case event tracking is not populate.

Any work around exist to work with ngBindHtml + analytics-on?

Sincerely,

**Comment by timelf123** [comment]
You could try to `interpolate` the html string in the controller - or write a directive wrapper that does that
