### ISSUE TITLE
Angulartics + Heap Analytics?

### ISSUE THREAD

**Issue by ChristoRibeiro** [angulartics/angulartics#543]
Is there a plugin for heap analytics? and works with bower?

**Comment by dkordik** [comment]
Per your first question, there's a very basic one at `/src/angulartics-heap.js`- see a usage example in the /samples folder: https://github.com/angulartics/angulartics/blob/master/samples/heap.html

**Comment by dkordik** [comment]
@chrissom as for bower configuration, check out this comment in another issue: https://github.com/angulartics/angulartics/issues/451#issuecomment-280766248
