### ISSUE TITLE
gaAnalytics.startTrackerWithId is not a function

### ISSUE THREAD

**Issue by alejandromagnorsky** [angulartics/angulartics#549]
When using angulartics-ga-cordova-google-analytics-plugin.js (v1.4.0) I get this error in the browser:
`gaAnalytics.startTrackerWithId is not a function`

Also, If I don't put the script in the index.html (which wasn't required in v1.1.2):
```
<script>
    (function(i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r;
        i[r] = i[r] || function() {
            (i[r].q = i[r].q || []).push(arguments)
        }, i[r].l = 1 * new Date();
        a = s.createElement(o),
            m = s.getElementsByTagName(o)[0];
        a.async = 1;
        a.src = g;
        m.parentNode.insertBefore(a, m)
    })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');
</script>
```
it crashes even earlier saying:
`ga is not defined`

It's worth to mention that this error doesn't happen in the mobile device (as an app).

**Comment by timelf123** [comment]
See https://github.com/danwilson/google-analytics-plugin/issues/107 - I don't think this plugin loads in the browser

**Comment by alejandromagnorsky** [comment]
Still, in that case it shouldn't throw an error.
I believe it needs to be fixed in the angulartics-ga-cordova-google-analytics-plugin.js file, probably by just adding something like:
`if(typeof analytics !== 'undefined')`
