### ISSUE TITLE
Misleading version of angulartics-gtm.min.js in dist folder

### ISSUE THREAD

**Issue by nvivo** [angulartics/angulartics#551]
Just spend a few hours trying to find out why the userId was not being sent to GA. The reason ended up being that I was using the script on the dist folder:

https://github.com/angulartics/angulartics/blob/master/dist/angulartics-gtm.min.js

instead of the one in it's own repository:

https://github.com/angulartics/angulartics-google-tag-manager/blob/master/dist/angulartics-google-tag-manager.min.js

The version on the dist folder is at least 2 years older and doesn't have any of the changed made since then. Having this folder on NPM and cdnjs is quite misleading.

It should either have the latest versions of all scripts or should have none and require us to install from each repository independently. I wonder if the other plugins are also out of date and causing similar problems.

**Comment by timelf123** [comment]
see https://github.com/angulartics/angulartics/pull/552 sorry for confusion - will cut a new release with these changes shortly
