### ISSUE TITLE
Doesn't work with AdBlock in Chrome

### ISSUE THREAD

**Issue by sptjohn** [angulartics/angulartics#58]
Hi

I'm currently using Angulartics in my web application, and one of my users is having problems.

He's getting a JavaScript exception saying "Uncaught Error: No module: angulartics.google.analytics".

He's managed to narrow it down to being related to AdBblock, and more specifically because of EasyPrivacy (privacy protection):

```
Resource: http://justabacklog.com/Scripts/analytics/angulartics-google-analytics.min.js
Type: script
Matched filter: -google-analytics.
Third-party: No
```

If he whitelists the script then everything works.

Regards

John

**Comment by pencilcheck** [comment]
I essentially have to rename the folder as well

**Comment by timelf123** [comment]
You should also be able to get around most of these filters by concatenating the contents of Angulartics into another file

**Comment by EvanTedesco** [comment]
Forgive my ignorance but where exactly should I be renaming angulartics-google-analytics.min.js to angulartics-ga.min.js?  Sorry I am not super familiar with the angular ecosystem and I recently encountered this issue.
