### ISSUE TITLE
Support beyond AngularJS 1.0.8

### ISSUE THREAD

**Issue by ghost** [angulartics/angulartics#85]
Angulartics seems to support the 1.1.x branch of Angular, but becomes unstable once you upgrade to the 1.2.x branch of Angular. By unstable, I mean it doesn't work at all.

You can reproduce the issue by downloading the demo application and switching out 1.0.7 for 1.2.0 or higher http://angulartics.herokuapp.com/google-analytics.html#/

**Comment by ElanHasson** [comment]
The resolution by @gh-naylor doesn't work for 1.3.30..
