### ISSUE TITLE
double tracking first pageview causes zero bounce rate in google analytics

### ISSUE THREAD

**Issue by hamtie** [angulartics/angulartics#97]
I've been trying to debug why my bounce rate has gone to zero since using angulartics.  Initially I thought it was my events tracking, which was not the case.  I discovered that this line was being called twice on the first page load: https://github.com/luisfarzati/angulartics/blob/master/src/angulartics-ga.js#L23

I know that there's the `autoTrackFirstPage` option as well as the `autoTrackVirtualPages` option.  I assumed that with these two options configured to true, there would still be only one pageview tracked on the initial load.  Is this assumption incorrect?

Can the docs clarify this if that's the case?

**Comment by stianlp** [comment]
Thanks so much! I've been wondering what the double tracking in ga was for a while. Thanks!

**Comment by timelf123** [comment]
@stianlp were you running an older version of Angulartics when you saw this problem?
